# default: 공통Common 적용
logging:
  level:
    io.honeymon.springboot.boot: DEBUG
server:
  port: 9000

---
# test profile 사용시 적용
spring:
  profiles: test
server:
  port: ${random.int[8000,9000}

---
# 개발서버 적용
spring:
  profiles: dev
server:
  port: 9000
  
---
# 운영서버 적용
spring:
  profiles: prod 
server:
  port: 5000  # AWS Elastic Beanstalk 에서는 5000번을 사용해야한다. 단 SERVER_PORT 로 정의해야 한다. 